import { expect } from 'chai';

/**
 * Mock implementation of the ZKPay smart contract generated by the Compact compiler.
 * Since we are testing in a standard TypeScript environment, this class simulates 
 * the on-chain ledger state, ZK circuit verification, and local witness data resolution.
 */
class ZKPayContractSimulator {
  public total_pool_value: bigint;
  public payees_commitments: Set<string>;

  constructor(initialPoolValue: bigint) {
    this.total_pool_value = initialPoolValue;
    // Simulate our Map<Bytes<32>, Boolean> representing the cryptographic set
    this.payees_commitments = new Set();
  }

  /**
   * Helper to simulate hashing payee data into a cryptographic commitment.
   * This corresponds to the `sha256(payee_address, allocated_amount, secret_key)`
   * call within the Compact circuit.
   */
  public static hashCommitment(address: string, amount: bigint, secret: string): string {
    // Mock hash implementation for deterministic testing
    return `hash(${address},${amount.toString()},${secret})`;
  }

  /**
   * Simulates the `claim_payroll` circuit logic and witness execution.
   */
  public claim_payroll(
    payee_address: string,
    claim_amount: bigint,
    secret_key: string,
    // The following parameter simulates data securely injected by the off-chain witness
    witness_allocated_amount: bigint
  ): void {
    // 1. Witness assertion: The claimed amount cannot exceed the private allocation
    if (witness_allocated_amount < claim_amount) {
      throw new Error("Claim exceeds allocated private balance");
    }

    // 2. Cryptographic assertion: Compute commitment and verify it exists on the public ledger
    const commitment = ZKPayContractSimulator.hashCommitment(payee_address, witness_allocated_amount, secret_key);
    
    if (!this.payees_commitments.has(commitment)) {
      throw new Error("Payee not found in the shielded set");
    }

    // 3. Pool validation for safety
    if (this.total_pool_value < claim_amount) {
      throw new Error("Insufficient total pool value");
    }

    // 4. State transition upon successful ZK proof verification
    this.total_pool_value -= claim_amount;
  }
}

describe('ZKPay Compact Contract Logic Tests', () => {
  let contract: ZKPayContractSimulator;
  const INITIAL_POOL_VALUE = 10_000n;

  // Mock data for our shielded payee
  const validPayee = {
    address: '0xPayeeAddress001',
    allocatedAmount: 1500n,
    secretKey: 'super-secret-key-42'
  };

  beforeEach(() => {
    // Deploy contract with 10,000 units
    contract = new ZKPayContractSimulator(INITIAL_POOL_VALUE);
    
    // Simulate adding the payee's commitment to the public ledger set
    const commitment = ZKPayContractSimulator.hashCommitment(
      validPayee.address,
      validPayee.allocatedAmount,
      validPayee.secretKey
    );
    contract.payees_commitments.add(commitment);
  });

  it('Test 1 (Initialization): should properly initialize the public payroll pool value', () => {
    expect(contract.total_pool_value).to.equal(INITIAL_POOL_VALUE);
    expect(contract.payees_commitments.size).to.equal(1);
  });

  it('Test 2 (Valid Shielded Claim): should succeed and decrement public pool balance for a valid claim', () => {
    const claimAmount = 500n;
    
    // Simulate successful witness resolution and circuit execution
    contract.claim_payroll(
      validPayee.address,
      claimAmount,
      validPayee.secretKey,
      validPayee.allocatedAmount // Injected by the mocked witness
    );

    // The public pool should be correctly decremented by 500n
    expect(contract.total_pool_value).to.equal(INITIAL_POOL_VALUE - claimAmount);
  });

  it('Test 3 (Invalid Fraudulent Claim): should catch unauthorized claims without altering state', () => {
    const excessiveClaim = 2000n; // Exceeds the 1500n allocation
    
    // 3a. Test an authorized user trying to claim more than their private allowance
    expect(() => {
      contract.claim_payroll(
        validPayee.address,
        excessiveClaim,
        validPayee.secretKey,
        validPayee.allocatedAmount
      );
    }).to.throw("Claim exceeds allocated private balance");

    // 3b. Test an adversarial scenario with an incorrect secret key
    const fraudulentClaimAmount = 100n;
    expect(() => {
      contract.claim_payroll(
        validPayee.address,
        fraudulentClaimAmount,
        'wrong-hacker-secret', 
        validPayee.allocatedAmount 
      );
    }).to.throw("Payee not found in the shielded set");

    // 3c. Ensure that the public ledger state remains strictly unaltered
    expect(contract.total_pool_value).to.equal(INITIAL_POOL_VALUE);
  });
});
